server.port=3000

spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://ranjanaditya336_db_user:BYVI7AFIqBYqQYSy@cluster0.s90uls1.mongodb.net/moviedb?retryWrites=true&w=majority}

jwt.secret=${JWT_SECRET:defaultsecretkey123456789012345678901234}
jwt.expiration=432000000

omdb.api.key=${API_KEY:defaultkey}
